In [11]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np

In [12]:
dataset=pd.read_csv("Netflix_clean.csv")

In [13]:
dataset

,customer_id,age,gender,subscription_type,watch_hours,last_login_days,region,device,monthly_fee,churned,payment_method,number_of_profiles,avg_watch_time_per_day,favorite_genre
0,a9b75100-82a8-427a-a208-72f24052884a,51,Other,Basic,14.73,29,Africa,TV,8.99,1,Gift Card,1,29,Action
1,49a5dfd9-7e69-4022-a6ad-0a1b9767fb5b,47,Other,Standard,0.70,19,Europe,Mobile,13.99,1,Gift Card,5,2,Sci-Fi
2,4d71f6ce-fca9-4ff7-8afa-197ac24de14b,27,Female,Standard,16.32,10,Asia,TV,13.99,0,Crypto,2,89,Drama
3,d3c72c38-631b-4f9e-8a0e-de103cad1a7d,53,Other,Premium,4.51,12,Oceania,TV,17.99,1,Crypto,2,21,Horror
4,4e265c34-103a-4dbb-9553-76c9aa47e946,56,Other,Standard,1.89,13,Africa,Mobile,13.99,1,Crypto,2,8,Action
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,44f3ba44-b95d-4e50-a786-bac4d06f4a43,19,Female,Basic,49.17,11,Europe,Desktop,8.99,0,Credit Card,4,246,Drama
4996,18779bcb-ba2b-41da-b751-e70b812061ec,67,Female,Basic,9.24,2,North America,Desktop,8.99,0,PayPal,3,185,Documentary
4997,3f32e8c5-615b-4a3b-a864-db2688f7834f,66,Male,Standard,16.55,49,South America,Desktop,13.99,1,Debit Card,2,20,Action
4998,7b0ad82d-6571-430e-90f4-906259e0e89c,59,Female,Basic,9.12,3,Europe,Laptop,8.99,0,Credit Card,4,137,Sci-Fi
4999,82aeef39-ddb0-40ad-bae1-5c436e0cf042,57,Male,Basic,1.62,17,Africa,Mobile,8.99,1,Crypto,2,5,Action

In [14]:
dataset.isnull().sum()

customer_id               0
age                       0
gender                    0
subscription_type         0
watch_hours               0
last_login_days           0
region                    0
device                    0
monthly_fee               0
churned                   0
payment_method            0
number_of_profiles        0
avg_watch_time_per_day    0
favorite_genre            0
dtype: int64

In [15]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             5000 non-null   object
 1   age                     5000 non-null   int64
 2   gender                  5000 non-null   object
 3   subscription_type       5000 non-null   object
 4   watch_hours             5000 non-null   float64
 5   last_login_days         5000 non-null   int64
 6   region                  5000 non-null   object
 7   device                  5000 non-null   object
 8   monthly_fee             5000 non-null   float64
 9   churned                 5000 non-null   int64
 10  payment_method          5000 non-null   object
 11  number_of_profiles      5000 non-null   int64
 12  avg_watch_time_per_day  5000 non-null   int64
 13  favorite_genre          5000 non-null   object
dtypes: float64(2), int64(5), object(7)
memory usage: 547.0+ KB

In [16]:
dataset.dtypes

customer_id                object
age                         int64
gender                     object
subscription_type          object
watch_hours               float64
last_login_days             int64
region                     object
device                     object
monthly_fee               float64
churned                     int64
payment_method             object
number_of_profiles          int64
avg_watch_time_per_day      int64
favorite_genre             object
dtype: object

In [17]:
Quan=[]
Qual=[]
for columnname in dataset.columns:
    if (dataset[columnname].dtype=='O'):
        
        Qual.append(columnname)
    else:
         
         Quan.append(columnname)

In [18]:
Qual,Quan

(['customer_id',
  'gender',
  'subscription_type',
  'region',
  'device',
  'payment_method',
  'favorite_genre'],
 ['age',
  'watch_hours',
  'last_login_days',
  'monthly_fee',
  'churned',
  'number_of_profiles',
  'avg_watch_time_per_day'])

In [19]:
def QuanQual(dataset):
    Quan=[]
    Qual=[]
    for columnname in dataset.columns:
        if (dataset[columnname].dtype=='O'):
            Qual.append(columnname)
        else:
             Quan.append(columnname)
    return Quan,Qual

In [20]:
quan,qual=QuanQual(dataset)

In [21]:
quan

['age',
 'watch_hours',
 'last_login_days',
 'monthly_fee',
 'churned',
 'number_of_profiles',
 'avg_watch_time_per_day']

In [22]:
float(dataset['watch_hours'].mean())

11.451039999999999

In [23]:
dataset['watch_hours'].median()

8.02

In [24]:
float(dataset['watch_hours'].mode()[0])

8.02

In [25]:
dataset.describe()

,age,watch_hours,last_login_days,monthly_fee,churned,number_of_profiles,avg_watch_time_per_day
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,43.902400,11.451040,30.154200,13.687600,0.503000,3.024400,49.203000
std,15.205562,11.688937,17.099909,3.693465,0.500041,1.415841,129.974598
min,18.000000,0.010000,0.000000,8.990000,0.000000,1.000000,0.000000
25%,31.000000,3.620000,16.000000,8.990000,0.000000,2.000000,7.000000
50%,44.000000,8.020000,30.000000,13.990000,1.000000,3.000000,17.000000
75%,57.000000,15.282500,44.000000,17.990000,1.000000,4.000000,41.000000
max,70.000000,110.400000,60.000000,17.990000,1.000000,5.000000,3168.000000

In [26]:
Descriptive=pd.DataFrame()

In [27]:
Descriptive

Empty DataFrame
Columns: []
Index: []

In [28]:
Descriptive=pd.DataFrame(index=['Mean','Median','Mode'],columns=quan)

In [29]:
Descriptive

,age,watch_hours,last_login_days,monthly_fee,churned,number_of_profiles,avg_watch_time_per_day
Mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mode,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
Descriptive=pd.DataFrame(index=['Mean','Median','Mode',"Q1:25%","Q2:50%","Q3:75%","99","Q4:100%","IQR","1.5Rule","Lesser","Greater","Min","Max"],columns=quan)
for columnname in quan:
    Descriptive.loc['Mean', columnname] = dataset[columnname].mean()
    Descriptive.loc['Median', columnname] = dataset[columnname].median()
    Descriptive.loc['Mode', columnname] = dataset[columnname].mode()[0]
    Descriptive.loc['Q1:25%', columnname] = dataset.describe()[columnname]["25%"]
    Descriptive.loc['Q2:50%', columnname] = dataset.describe()[columnname]["50%"]
    Descriptive.loc['Q3:75%', columnname] = dataset.describe()[columnname]["75%"]
    Descriptive.loc['99', columnname] = np.nanpercentile(dataset[columnname],99)
    Descriptive.loc['Q4:100%', columnname] = dataset.describe()[columnname]["max"]
    Descriptive.loc['IQR', columnname] = Descriptive.loc['Q3:75%', columnname]-Descriptive.loc['Q1:25%', columnname]
    Descriptive.loc['1.5Rule', columnname] = 1.5*  Descriptive.loc['IQR', columnname]
    Descriptive.loc['Lesser', columnname] = Descriptive.loc['Q1:25%', columnname]-Descriptive.loc['1.5Rule', columnname]
    Descriptive.loc['Greater', columnname] = Descriptive.loc['Q3:75%', columnname]+Descriptive.loc['1.5Rule', columnname]
    Descriptive.loc['Min', columnname] = dataset[columnname].min()
    Descriptive.loc['Max', columnname] = dataset[columnname].max()

In [31]:
Greater=[]
Lesser=[]
for columnname in quan:
    if(Descriptive[columnname]['Max']>Descriptive[columnname]['Greater']):
        Greater.append(columnname)
    if(Descriptive[columnname]['Min']<Descriptive[columnname]['Lesser']):
        Lesser.append(columnname)

In [32]:
Greater

['watch_hours', 'avg_watch_time_per_day']

In [33]:
for columnname in Greater:
    dataset[columnname][dataset[columnname]>Descriptive[columnname]['Greater']]=Descriptive[columnname]['Greater']

In [34]:
Descriptive=pd.DataFrame(index=['Mean','Median','Mode',"Q1:25%","Q2:50%","Q3:75%","99","Q4:100%","IQR","1.5Rule","Lesser","Greater","Min","Max"],columns=quan)
for columnname in quan:
    Descriptive.loc['Mean', columnname] = dataset[columnname].mean()
    Descriptive.loc['Median', columnname] = dataset[columnname].median()
    Descriptive.loc['Mode', columnname] = dataset[columnname].mode()[0]
    Descriptive.loc['Q1:25%', columnname] = dataset.describe()[columnname]["25%"]
    Descriptive.loc['Q2:50%', columnname] = dataset.describe()[columnname]["50%"]
    Descriptive.loc['Q3:75%', columnname] = dataset.describe()[columnname]["75%"]
    Descriptive.loc['99', columnname] = np.nanpercentile(dataset[columnname],99)
    Descriptive.loc['Q4:100%', columnname] = dataset.describe()[columnname]["max"]
    Descriptive.loc['IQR', columnname] = Descriptive.loc['Q3:75%', columnname]-Descriptive.loc['Q1:25%', columnname]
    Descriptive.loc['1.5Rule', columnname] = 1.5*  Descriptive.loc['IQR', columnname]
    Descriptive.loc['Lesser', columnname] = Descriptive.loc['Q1:25%', columnname]-Descriptive.loc['1.5Rule', columnname]
    Descriptive.loc['Greater', columnname] = Descriptive.loc['Q3:75%', columnname]+Descriptive.loc['1.5Rule', columnname]
    Descriptive.loc['Min', columnname] = dataset[columnname].min()
    Descriptive.loc['Max', columnname] = dataset[columnname].max()

In [35]:
 Descriptive

,age,watch_hours,last_login_days,monthly_fee,churned,number_of_profiles,avg_watch_time_per_day
Mean,43.9024,10.703503,30.1542,13.6876,0.503,3.0244,28.914
Median,44.0,8.02,30.0,13.99,1.0,3.0,17.0
Mode,44,8.02,30,17.99,1,5,92
Q1:25%,31.0,3.62,16.0,8.99,0.0,2.0,7.0
Q2:50%,44.0,8.02,30.0,13.99,1.0,3.0,17.0
Q3:75%,57.0,15.2825,44.0,17.99,1.0,4.0,41.0
99,70.0,32.77625,60.0,17.99,1.0,5.0,92.0
Q4:100%,70.0,32.77625,60.0,17.99,1.0,5.0,92.0
IQR,26.0,11.6625,28.0,9.0,1.0,2.0,34.0
1.5Rule,39.0,17.49375,42.0,13.5,1.5,3.0,51.0
Lesser,-8.0,-13.87375,-26.0,-4.51,-1.5,-1.0,-44.0
Greater,96.0,32.77625,86.0,31.49,2.5,7.0,92.0
Min,18,0.01,0,8.99,0,1,0
Max,70,32.77625,60,17.99,1,5,92

In [36]:
import numpy as np

In [37]:
np.percentile(dataset['age'],10)

np.float64(23.0)

In [38]:
np.nanpercentile(dataset['age'],3)

np.float64(19.0)

In [39]:
dataset['last_login_days'].value_counts().index

Index([30, 37, 44, 46, 26, 16, 53,  4, 54, 18, 39,  2, 40, 27, 10, 11, 20, 41,
       25, 24, 28,  1, 33, 23,  9, 34, 58, 36, 52, 48,  3, 49, 59,  6, 57, 47,
       45,  0, 22, 50, 21, 42, 13, 12, 55, 56, 43,  8, 32, 29, 51, 31, 60, 19,
       35,  5,  7, 38, 17, 14, 15],
      dtype='int64', name='last_login_days')

In [40]:
Frequency_Table=pd.DataFrame(columns=['Unique_Values','Frequency','Relative_Frequency','Cumsum'])

In [41]:
Frequency_Table

Empty DataFrame
Columns: [Unique_Values, Frequency, Relative_Frequency, Cumsum]
Index: []

In [42]:
Frequency_Table['Unique_Values']=dataset['monthly_fee'].value_counts().index
Frequency_Table['Frequency']=dataset['monthly_fee'].value_counts().values
Frequency_Table['Relative_Frequency']=Frequency_Table['Frequency']/61
Frequency_Table['Cumsum']=Frequency_Table['Relative_Frequency'].cumsum()

In [43]:
def Frequency_Table(columnname,dataset):
    Frequency_Table=pd.DataFrame(columns=['Unique_Values','Frequency','Relative_Frequency','Cumsum'])
    Frequency_Table['Unique_Values']=dataset[columnname].value_counts().index
    Frequency_Table['Frequency']=dataset[columnname].value_counts().values
    Frequency_Table['Relative_Frequency']=Frequency_Table['Frequency']/61
    Frequency_Table['Cumsum']=Frequency_Table['Relative_Frequency'].cumsum()
    return Frequency_Table

In [44]:
Frequency_Table('number_of_profiles',dataset)

   Unique_Values  Frequency  Relative_Frequency     Cumsum
0              5       1034           16.950820  16.950820
1              2       1001           16.409836  33.360656
2              4        999           16.377049  49.737705
3              3        994           16.295082  66.032787
4              1        972           15.934426  81.967213

In [45]:
dataset['number_of_profiles'].skew()

np.float64(-0.016894873164998485)

In [46]:
dataset['number_of_profiles'].kurtosis()

np.float64(-1.3030664887095968)

In [47]:
Descriptive=pd.DataFrame(index=['Mean','Median','Mode',"Q1:25%","Q2:50%","Q3:75%","99","Q4:100%","IQR","1.5Rule","Lesser","Greater","Min","Max","Skew","Kurtosis"],columns=quan)
for columnname in quan:
    Descriptive.loc['Mean', columnname] = dataset[columnname].mean()
    Descriptive.loc['Median', columnname] = dataset[columnname].median()
    Descriptive.loc['Mode', columnname] = dataset[columnname].mode()[0]
    Descriptive.loc['Q1:25%', columnname] = dataset.describe()[columnname]["25%"]
    Descriptive.loc['Q2:50%', columnname] = dataset.describe()[columnname]["50%"]
    Descriptive.loc['Q3:75%', columnname] = dataset.describe()[columnname]["75%"]
    Descriptive.loc['99', columnname] = np.nanpercentile(dataset[columnname],99)
    Descriptive.loc['Q4:100%', columnname] = dataset.describe()[columnname]["max"]
    Descriptive.loc['IQR', columnname] = Descriptive.loc['Q3:75%', columnname]-Descriptive.loc['Q1:25%', columnname]
    Descriptive.loc['1.5Rule', columnname] = 1.5*  Descriptive.loc['IQR', columnname]
    Descriptive.loc['Lesser', columnname] = Descriptive.loc['Q1:25%', columnname]-Descriptive.loc['1.5Rule', columnname]
    Descriptive.loc['Greater', columnname] = Descriptive.loc['Q3:75%', columnname]+Descriptive.loc['1.5Rule', columnname]
    Descriptive.loc['Min', columnname] = dataset[columnname].min()
    Descriptive.loc['Max', columnname] = dataset[columnname].max()
    Descriptive.loc['Skew', columnname] = dataset[columnname].skew()
    Descriptive.loc['Kurtosis', columnname] = dataset[columnname].kurtosis()

In [48]:
Descriptive

,age,watch_hours,last_login_days,monthly_fee,churned,number_of_profiles,avg_watch_time_per_day
Mean,43.9024,10.703503,30.1542,13.6876,0.503,3.0244,28.914
Median,44.0,8.02,30.0,13.99,1.0,3.0,17.0
Mode,44,8.02,30,17.99,1,5,92
Q1:25%,31.0,3.62,16.0,8.99,0.0,2.0,7.0
Q2:50%,44.0,8.02,30.0,13.99,1.0,3.0,17.0
Q3:75%,57.0,15.2825,44.0,17.99,1.0,4.0,41.0
99,70.0,32.77625,60.0,17.99,1.0,5.0,92.0
Q4:100%,70.0,32.77625,60.0,17.99,1.0,5.0,92.0
IQR,26.0,11.6625,28.0,9.0,1.0,2.0,34.0
1.5Rule,39.0,17.49375,42.0,13.5,1.5,3.0,51.0
Lesser,-8.0,-13.87375,-26.0,-4.51,-1.5,-1.0,-44.0
Greater,96.0,32.77625,86.0,31.49,2.5,7.0,92.0
Min,18,0.01,0,8.99,0,1,0
Max,70,32.77625,60,17.99,1,5,92
Skew,-0.002188,1.044531,-0.030247,-0.14651,-0.012004,-0.016895,1.180311
Kurtosis,-1.174904,0.152006,-1.091453,-1.506008,-2.000656,-1.303066,0.082218

In [49]:
dataset.to_csv("Netflix_cleaned.csv", index=False)